name: 🚀 Deploy website on push

on:
  push:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist


    - name: Install Npm
      run: npm install

    - name: Compile Css and Js Assets
      run: npm run build

    - name: Adjust index.php paths and move public contents
      run: |
        # Adjust paths in index.php
        sed -i "s|require __DIR__\.'/../vendor/autoload.php';|require __DIR__ . '/vendor/autoload.php';|g" public/index.php
        sed -i "s|require_once __DIR__\.'/../bootstrap/app.php';|require_once __DIR__ . '/bootstrap/app.php';|g" public/index.php

          # Move contents of public to the root directory, excluding special entries
         shopt -s dotglob
         shopt -s extglob
         mv -v public/!(.|..) ./
         shopt -u dotglob
         shopt -u extglob

        # Remove the now-empty public directory
        rmdir public || true

    - name: Set directory permissions
      run: |
        chmod -R 775 storage
        chmod -R 775 bootstrap/cache

    - name: Clear Laravel Cache
      run: |
        php artisan config:clear
        php artisan cache:clear
        php artisan route:clear
        php artisan view:clear

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.logicbloom.co.za
        username: admin@logicbloom.co.za
        password: 51420841Lu@
        server-dir: /public_html/
